package com.bankingsystem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.Scanner;

public class Accounts {

    private Connection connection;
    private Scanner scanner;
    private PreparedStatement preparedStatement;


    public Accounts(Connection connection, Scanner scanner, PreparedStatement preparedStatement){
        this.connection = connection;
        this.scanner = scanner;
        this.preparedStatement = preparedStatement;
    }

    public long open_account(String number){

        if(!account_exist(number)) {
            String open_account_query = BasicSQL.OPEN_ACC;

            scanner.nextLine();
            System.out.print("Enter Full Name: ");
            String full_name = scanner.nextLine();
            System.out.print("Enter Initial Amount: ");
            double balance = scanner.nextDouble();
            scanner.nextLine();
            System.out.println("Enter Email: ");
            String email = scanner.nextLine();
            System.out.print("Enter Security Pin: ");
            String security_pin = scanner.nextLine();

            try {
                long account_number = generateAccountNumber();
                preparedStatement = connection.prepareStatement(open_account_query);
                preparedStatement.setLong(1, account_number);
                preparedStatement.setString(2, full_name);
                preparedStatement.setString(3, email);
                preparedStatement.setString(4, number);
                preparedStatement.setDouble(5, balance);
                preparedStatement.setString(6, security_pin);
                int rowsAffected = preparedStatement.executeUpdate();
                if (rowsAffected > 0) {
                    return account_number;
                } else {
                    System.out.println();
                    throw new RuntimeException("Account Creation failed!!");
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        System.out.println();
        throw new RuntimeException("Account Already Exist");
    }

    public long getAccount_number(String number) {

        String query = BasicSQL.GET_ACC;
        try{
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, number);
            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                return resultSet.getLong("account_number");
            }
        }catch (SQLException e){
            e.printStackTrace();
        }
        System.out.println();
        throw new RuntimeException("Account Number Doesn't Exist!");
    }

    private long generateAccountNumber() throws SQLException {

        Random random = new Random();
        long accountNumber;
        boolean isUnique;

//        // Insert the customer name (account number is auto-generated by trigger)
//        String insertQuery = BasicSQL.GENERATE_ACCOUNT_NUMBER;
//        try {
//            preparedStatement = connection.prepareStatement(insertQuery);
//            preparedStatement.setString(1, number);
//            preparedStatement.executeUpdate();
//        }catch (SQLException e){
//            e.printStackTrace();
//        }
//
//        // Fetch the last inserted account number for the given customer
//        String selectQuery = BasicSQL.GET_ACC;
//        try{
//            preparedStatement = connection.prepareStatement(selectQuery);
//            preparedStatement.setString(1, number);
//            ResultSet resultSet = preparedStatement.executeQuery();
//
//            if (resultSet.next()){
//                accountNumber = resultSet.getLong(1);
//            }
        do {
            // Generate a 12-digit random number
            accountNumber = 100000000000L + (long) (random.nextDouble() * 900000000000L);

            // Check if the account number already exists
            String checkQuery = BasicSQL.CHECK;
            try {
                preparedStatement = connection.prepareStatement(checkQuery);
                preparedStatement.setLong(1, accountNumber);
                ResultSet rs = preparedStatement.executeQuery();
                rs.next();
                isUnique = rs.getInt(1) == 0; // Unique if count is 0
            } catch (SQLException e) {
                e.printStackTrace();
                return -1;
            }
        }while (!isUnique) ; // Repeat if not unique

            return accountNumber;
        }

    public boolean account_exist(String number){

        String query = BasicSQL.ACC_EXIST;

        try{
            preparedStatement = connection.prepareStatement(query);
            preparedStatement.setString(1, number);
            ResultSet resultSet = preparedStatement.executeQuery();

            if(resultSet.next()){
                return true;
            }else{
                return false;
            }

        }catch (SQLException e){
            e.printStackTrace();
        }
        return false;

    }

}




